<template>
  <div class="container-realizations">
    <div class="container row" id="bp">
      <h1>BP</h1>
      <div class="column">
        <img src="/img/01bp/bp-7.jpg" @click="showMultiple(4)" />
        <img src="/img/01bp/bp-11.jpg" @click="showMultiple(1)" />
      </div>
      <div class="column">
        <img src="/img/01bp/bp-8.jpg" @click="showMultiple(5)" />
        <img src="/img/01bp/bp-12.jpg" @click="showMultiple(2)" />
      </div>
      <div class="column">
        <img src="/img/01bp/bp-9.jpg" @click="showMultiple(6)" />
        <img src="/img/01bp/bp-13.jpg" @click="showMultiple(3)" />
      </div>
      <div class="column">
        <img src="/img/01bp/bp-10.jpg" @click="showMultiple(0)" />
      </div>
    </div>
    <div class="container row" id="bank">
      <h1>Bank</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/02bank_bgz/bank-0.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(7)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/02bank_bgz/bank-4.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(12)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/02bank_bgz/bank-8.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(16)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/02bank_bgz/bank-1.jpg"
          alt="Drewno"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(8)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/02bank_bgz/bank-5.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(13)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/02bank_bgz/bank-9.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(17)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/02bank_bgz/bank-2.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(10)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/02bank_bgz/bank-6.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(14)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/02bank_bgz/bank-10.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(9)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/02bank_bgz/bank-3.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(11)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/02bank_bgz/bank-7.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(15)"
        >
        </lazy-image>
      </div>
    </div>
    <div class="container row" id="biblioteka">
      <h1>Biblioteka</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/03biblioteka/biblioteka-1.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(18)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/03biblioteka/biblioteka-2.jpg"
          alt="Drewno"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(19)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/03biblioteka/biblioteka-3.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(20)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/03biblioteka/biblioteka-4.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(21)"
        >
        </lazy-image>
      </div>
    </div>
    <div class="container row" id="domy">
      <h1>Domy</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-1.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(23)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-5.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(31)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-9.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(35)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-2.jpg"
          alt="Drewno"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(28)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-6.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(26)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-10.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(24)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-3.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(29)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-11.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(25)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-7.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(33)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-12.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(26)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-4.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(30)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-8.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(34)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/04domy/domy-13.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(27)"
        >
        </lazy-image>
      </div>
    </div>
    <div class="container row" id="garderoba">
      <h1>Garderoba</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/05garderoba/garderoba-1.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(36)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/05garderoba/garderoba-2.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(37)"
        >
        </lazy-image>
      </div>
    </div>
    <div class="container row" id="kuchnieStyl">
      <h1>Kuchnie Stylowe</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-1.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(38)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-5.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(48)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-9.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(52)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-12.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(41)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-2.jpg"
          alt="Drewno"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(45)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-6.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(49)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-10.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(39)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-13.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(42)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-3.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(46)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-7.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(50)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-11.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(40)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-14.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(43)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-4.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(47)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-8.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(51)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-12.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(41)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/06kuchnia_stylowa/KuchniaStyl-15.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(44)"
        >
        </lazy-image>
      </div>
    </div>
    <div class="container row" id="kuchnie">
      <h1>Kuchnie</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/07kuchnie/kuchnie-1.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(53)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/07kuchnie/kuchnie-5.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(86)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/07kuchnie/kuchnie-9.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(90)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/07kuchnie/kuchnie-2.jpg"
          alt="Drewno"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(64)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/07kuchnie/kuchnie-6.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(87)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/07kuchnie/kuchnie-10.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(54)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/07kuchnie/kuchnie-3.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(75)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/07kuchnie/kuchnie-7.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(88)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/07kuchnie/kuchnie-11.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(55)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/07kuchnie/kuchnie-4.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(85)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/07kuchnie/kuchnie-8.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(89)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/07kuchnie/kuchnie-12.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(56)"
        >
        </lazy-image>
      </div>
    </div>
    <div class="container row" id="lada">
      <h1>Lada</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/09lada/lada-1.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(101)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/09lada/lada-5.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(105)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/09lada/lada-2.jpg"
          alt="Drewno"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(102)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/09lada/lada-6.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(106)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/09lada/lada-3.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(103)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/09lada/lada-7.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(107)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/09lada/lada-4.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(104)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/09lada/lada-8.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(108)"
        >
        </lazy-image>
      </div>
    </div>
    <div class="container row" id="lazienka">
      <h1>Łazienki</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/10lazienka/lazienka-1.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(110)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/10lazienka/lazienka-5.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(114)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/10lazienka/lazienka-2.jpg"
          alt="Drewno"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(111)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/10lazienka/lazienka-6.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(115)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/10lazienka/lazienka-3.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(112)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/10lazienka/lazienka-7.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(116)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/10lazienka/lazienka-4.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(113)"
        >
        </lazy-image>
      </div>
    </div>
    <div class="container row" id="metalowe">
      <h1>Meble Metalowe</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/11metalowe/metalowe-1.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(117)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/11metalowe/metalowe-2.jpg"
          alt="Drewno"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(118)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/11metalowe/metalowe-3.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(119)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/11metalowe/metalowe-4.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(120)"
        >
        </lazy-image>
      </div>
    </div>
    <div class="container row" id="miniakad">
      <h1>Mini Akademik</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-1.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(120)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-5.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(156)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-9.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(181)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-13.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(126)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-17.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(130)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-21.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(135)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-2.jpg"
          alt="Drewno"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(133)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-6.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(157)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-10.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(123)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-14.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(127)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-18.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(131)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-22.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(136)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-3.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(144)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-7.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(167)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-11.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(124)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-15.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(128)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-19.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(132)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-23.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(137)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-4.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(155)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-8.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(178)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-12.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(125)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-16.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(129)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-20.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(134)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/12mini_akademik/miniakad-24.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(138)"
        >
        </lazy-image>
      </div>
    </div>
    <div class="container row" id="pokoj">
      <h1>Pokoje</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-1.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(192)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-5.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(200)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-9.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(204)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-13.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(200)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-17.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(204)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-21.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(204)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-2.jpg"
          alt="Drewno"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(197)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-6.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(201)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-10.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(193)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-14.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(200)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-18.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(204)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-22.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(204)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-3.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(198)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-7.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(202)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-11.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(194)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-16.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(200)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-19.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(204)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-23.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(204)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-4.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(199)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-8.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(203)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-12.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(195)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-16.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(200)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/13pokoj/pokoj-20.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(204)"
        >
        </lazy-image>
      </div>
    </div>
    <div class="container row" id="standy">
      <h1>Standy Reklamowe</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-1.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(206)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-5.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(222)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-9.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(226)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-13.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(226)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-17.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(226)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-21.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(226)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-2.jpg"
          alt="Drewno"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(217)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-6.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(223)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-10.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(207)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-14.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(226)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-18.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(226)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-3.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(220)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-7.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(224)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-11.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(208)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-15.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(226)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-19.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(226)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-4.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(221)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-8.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(225)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-12.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(209)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-16.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(226)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/14standy_reklamowe/standy-20.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(226)"
        >
        </lazy-image>
      </div>
    </div>
    <div class="container row" id="szafy">
      <h1>Szafy i Szafki</h1>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-1.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-5.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-9.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-13.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-17.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-21.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-2.jpg"
          alt="Drewno"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(238)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-6.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-10.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-14.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-18.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-22.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-3.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(249)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-7.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-11.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-15.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-19.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-23.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
      </div>
      <div class="column">
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-4.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(258)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-8.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-12.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-16.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-20.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
        <lazy-image
          initial-image="/img/loading.svg"
          final-image="/img/15szafy_szafki/SzaftISzafki-24.jpg"
          alt="Test1"
          :blur-amount="2"
          class="klasa"
          @click="showMultiple(227)"
        >
        </lazy-image>
      </div>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
</template>

<script>
import VueEasyLightbox from "vue-easy-lightbox";
import LazyImage from "./comps/LazyImage";
import axios from "axios";

export default {
  components: {
    LazyImage,
    VueEasyLightbox,
  },
  data() {
    return {
      imgs: [], // Img Url , string or Array of string
      visible: false,
      index: 0, // default: 0
    };
  },
  mounted() {
    this.images();
  },
  methods: {
    images: function () {
      axios.get("/api/images").then((response) => {
        this.resp = response.data.data;
        let ok = 0;
        for (let i = 0; i < this.resp.length; i++) {
          this.respImages = this.resp[i].images;
          for (let j = 0; j < this.respImages.length; j++) {
            console.log(
              ok + ". " + this.resp[i].realisation + "/" + this.respImages[j]
            );
            ok++;
            this.imgs.push(
              "/img/" + this.resp[i].realisation + "/" + this.respImages[j]
            );
          }
        }
        // console.log(this.resp);
      });
    },
    showMultiple(index) {
      // allow mixing

      this.index = index; // index of imgList
      this.show();
    },
    show() {
      this.visible = true;
    },
    handleHide() {
      this.visible = false;
    },
  },
};
</script>

<style scoped>
</style>
