<template>
  <div class="container row">
    <h1>Bank</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-0.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-1.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-2.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
  <div class="container row">
    <h1>Biblioteka</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/biblioteka/biblioteka-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/biblioteka/biblioteka-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/biblioteka/biblioteka-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/biblioteka/biblioteka-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
  <div class="container row">
    <h1>BP</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-8.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-13.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
  <div class="container row">
    <h1>Domy</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-13.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
  <div class="container row">
    <h1>Garderoba</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/garderoba/garderoba-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/garderoba/garderoba-2.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
  <div class="container row">
    <h1>Kuchnie Stylowe</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-13.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-14.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-15.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
  <div class="container row">
    <h1>Kuchnie</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
  <div class="container row">
    <h1>Lada</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
  <div class="container row">
    <h1>Łazienki</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Meble Metalowe</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/metalowe/metalowe-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/metalowe/metalowe-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/metalowe/metalowe-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/metalowe/metalowe-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
  <div class="container row">
    <h1>Mini Akademik</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-13.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-17.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-21.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-14.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-18.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-22.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-15.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-19.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-23.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-16.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-20.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-24.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
  <div class="container row">
    <h1>Pokoje</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
  <div class="container row">
    <h1>Standy Reklamowe</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
  <div class="container row">
    <h1>Szafy i Szafki</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/szafy_szafki/SzaftISzafki-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/szafy_szafki/SzaftISzafki-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/szafy_szafki/SzaftISzafki-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/szafy_szafki/SzaftISzafki-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
  </div>
</template>

<script>
import VueEasyLightbox from "vue-easy-lightbox";
import LazyImage from "./comps/LazyImage";

export default {
  components: {
    LazyImage,
    VueEasyLightbox,
  },
  data() {
    return {
      imgs: "", // Img Url , string or Array of string
      visible: false,
      index: 0, // default: 0
    };
  },
  methods: {
    showMultiple(index) {
      this.imgs = [
        { title: "test img", src: "/img/test.png" },
        { title: "test img", src: "/img/test2.png" },
        { title: "test img", src: "/img/test3.png" },
        { title: "test img", src: "/img/test4.png" },
        { title: "test img", src: "/img/wood.jpg" },
      ];
      // allow mixing

      this.index = index; // index of imgList
      this.show();
    },
    show() {
      this.visible = true;
    },
    handleHide() {
      this.visible = false;
    },
  },
};
</script>

<style scoped>
</style>
