<template>
  <div class="container row">
    <h1>Bank</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-0.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(0)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(1)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(2)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-1.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(3)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(4)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(5)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-2.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(6)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(7)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(8)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(9)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bank_bgz/bank-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(10)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Biblioteka</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/biblioteka/biblioteka-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(11)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/biblioteka/biblioteka-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(12)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/biblioteka/biblioteka-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(13)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/biblioteka/biblioteka-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(14)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>BP</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(15)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(16)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-8.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(17)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(18)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(19)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-13.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(20)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/bp/bp-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(21)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Domy</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(22)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(23)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(24)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(25)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(26)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(27)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(28)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(29)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(30)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(31)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(32)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(33)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/domy/domy-13.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(34)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Garderoba</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/garderoba/garderoba-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(35)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/garderoba/garderoba-2.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(36)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Kuchnie Stylowe</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(37)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(38)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(39)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(40)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(41)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(42)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(43)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-13.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(44)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(45)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(46)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(47)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-14.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(48)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(49)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(50)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(51)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/Kuchnia_Stylowa/KuchniaStyl-15.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(52)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Kuchnie</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(53)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(54)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(55)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(56)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(57)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(58)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(59)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(60)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(61)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(62)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(63)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/kuchnie/kuchnie-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(64)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Lada</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(65)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(66)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(67)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(68)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(69)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(70)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(71)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lada/lada-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(72)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Łazienki</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(73)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(74)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(75)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(76)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(77)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(78)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/lazienka/lazienka-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(79)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Meble Metalowe</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/metalowe/metalowe-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(80)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/metalowe/metalowe-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(81)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/metalowe/metalowe-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(82)"
      >
      </lazy-image>
      <vue-easy-lightbox
        scrollDisabled
        escDisabled
        moveDisabled
        :visible="visible"
        :imgs="imgs"
        :index="index"
        @hide="handleHide"
      ></vue-easy-lightbox>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/metalowe/metalowe-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(83)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Mini Akademik</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(84)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(85)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(86)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-13.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(87)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-17.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(88)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-21.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(89)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(90)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(91)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(92)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-14.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(93)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-18.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(94)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-22.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(95)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(96)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(97)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(98)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-15.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(99)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-19.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(100)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-23.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(101)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(102)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(103)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(104)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-16.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(105)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-20.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(106)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/mini_akademik/miniakad-24.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(107)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Pokoje</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(108)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(109)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(110)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(111)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(112)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(113)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(114)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(115)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(116)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(117)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(118)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/pokoj/pokoj-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(119)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Standy Reklamowe</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(120)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-5.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(121)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-9.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(122)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(123)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-6.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(124)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-10.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(125)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(126)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-7.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(127)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-11.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(128)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(129)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-8.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(130)"
      >
      </lazy-image>
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/standy_reklamowe/standy-12.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(131)"
      >
      </lazy-image>
    </div>
  </div>
  <div class="container row">
    <h1>Szafy i Szafki</h1>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/szafy_szafki/SzaftISzafki-1.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(132)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/szafy_szafki/SzaftISzafki-2.jpg"
        alt="Drewno"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(133)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/szafy_szafki/SzaftISzafki-3.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(134)"
      >
      </lazy-image>
    </div>
    <div class="column">
      <lazy-image
        initial-image="/img/load.gif"
        final-image="/img/szafy_szafki/SzaftISzafki-4.jpg"
        alt="Test1"
        :blur-amount="2"
        class="klasa"
        @click="showMultiple(135)"
      >
      </lazy-image>
    </div>
      <vue-easy-lightbox
          scrollDisabled
          escDisabled
          moveDisabled
          :visible="visible"
          :imgs="imgs"
          :index="index"
          @hide="handleHide"
      ></vue-easy-lightbox>
  </div>
</template>

<script>
import VueEasyLightbox from "vue-easy-lightbox";
import LazyImage from "./comps/LazyImage";
import axios from 'axios';

export default {
  components: {
    LazyImage,
    VueEasyLightbox,
  },
  data() {
    return {
      imgs: [], // Img Url , string or Array of string
      visible: false,
      index: 0, // default: 0
    };
  },
    mounted() {
        this.images();
    },
    methods: {
    images: function () {
        axios.get("/api/images")
            .then((response) => {
                this.resp = response.data.data;
                for(let i = 0; i<this.resp.length;i++){
                    this.respImages = this.resp[i].images;
                    for(let j = 0;j<this.respImages.length;j++){
                        // console.log(this.resp[i].realisation+"/"+this.respImages[j]);
                        this.imgs.push('/img/'+this.resp[i].realisation+'/'+this.respImages[j]);
                    }
                }
                // console.log(this.resp);
            });
    },
    showMultiple(index) {

      // allow mixing

      this.index = index; // index of imgList
      this.show();
    },
    show() {
      this.visible = true;
    },
    handleHide() {
      this.visible = false;
    },
  },
};
</script>

<style scoped>
</style>
